// ISO 3166-1 alpha-2 country codes for Flagpack
export const countryCodeMap: Record<string, string> = {
  "Afghanistan": "af",
  "Albania": "al",
  "Algeria": "dz",
  "Argentina": "ar",
  "Australia": "au",
  "Austria": "at",
  "Azerbaijan": "az",
  "Bangladesh": "bd",
  "Belarus": "by",
  "Belgium": "be",
  "Bolivia": "bo",
  "Brazil": "br",
  "Bulgaria": "bg",
  "Cambodia": "kh",
  "Cameroon": "cm",
  "Canada": "ca",
  "Chile": "cl",
  "China": "cn",
  "Colombia": "co",
  "Costa Rica": "cr",
  "Croatia": "hr",
  "Cuba": "cu",
  "Czech Republic": "cz",
  "Denmark": "dk",
  "Dominican Republic": "do",
  "Ecuador": "ec",
  "Egypt": "eg",
  "El Salvador": "sv",
  "Estonia": "ee",
  "Ethiopia": "et",
  "Finland": "fi",
  "France": "fr",
  "Georgia": "ge",
  "Germany": "de",
  "Ghana": "gh",
  "Greece": "gr",
  "Guatemala": "gt",
  "Haiti": "ht",
  "Honduras": "hn",
  "Hong Kong": "hk",
  "Hungary": "hu",
  "Iceland": "is",
  "India": "in",
  "Indonesia": "id",
  "Iran": "ir",
  "Iraq": "iq",
  "Ireland": "ie",
  "Israel": "il",
  "Italy": "it",
  "Jamaica": "jm",
  "Japan": "jp",
  "Jordan": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Kuwait": "kw",
  "Laos": "la",
  "Latvia": "lv",
  "Lebanon": "lb",
  "Libya": "ly",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Malaysia": "my",
  "Maldives": "mv",
  "Malta": "mt",
  "Mexico": "mx",
  "Mongolia": "mn",
  "Morocco": "ma",
  "Myanmar": "mm",
  "Nepal": "np",
  "Netherlands": "nl",
  "New Zealand": "nz",
  "Nicaragua": "ni",
  "Nigeria": "ng",
  "North Korea": "kp",
  "Norway": "no",
  "Pakistan": "pk",
  "Panama": "pa",
  "Paraguay": "py",
  "Peru": "pe",
  "Philippines": "ph",
  "Poland": "pl",
  "Portugal": "pt",
  "Puerto Rico": "pr",
  "Qatar": "qa",
  "Romania": "ro",
  "Russia": "ru",
  "Saudi Arabia": "sa",
  "Senegal": "sn",
  "Serbia": "rs",
  "Singapore": "sg",
  "Slovakia": "sk",
  "Slovenia": "si",
  "South Africa": "za",
  "South Korea": "kr",
  "Spain": "es",
  "Sri Lanka": "lk",
  "Sweden": "se",
  "Switzerland": "ch",
  "Syria": "sy",
  "Taiwan": "tw",
  "Tanzania": "tz",
  "Thailand": "th",
  "Tunisia": "tn",
  "Turkey": "tr",
  "Ukraine": "ua",
  "United Arab Emirates": "ae",
  "United Kingdom": "gb",
  "United States": "us",
  "Uruguay": "uy",
  "Uzbekistan": "uz",
  "Venezuela": "ve",
  "Vietnam": "vn",
  "Yemen": "ye",
  "Zimbabwe": "zw",
  "Other": "xx" // Custom code for "Other"
}

// Country list with names and codes
export const countries = Object.entries(countryCodeMap).map(([name, code]) => ({
  name,
  code
}))

// Get ISO code for a country name
export function getCountryCode(countryName: string): string {
  return countryCodeMap[countryName] || "xx"
} 